language: node_js
node_js:
- '10.13.0'
branches:
  only:
  - main

addons:
  chrome: stable

before_script:
- yarn global add @angular/cli

cache:
  yarn: true
  directories:
  - node_modules

script:
- npm run lint
- ng test --watch=false
